// 114 Surah Al-Quran lengkap
export const DAFTAR_SURAH = [
  { nomor: 1, nama: 'Al-Fatihah', arti: 'Pembukaan' },
  { nomor: 2, nama: 'Al-Baqarah', arti: 'Sapi Betina' },
  { nomor: 3, nama: 'Ali Imran', arti: 'Keluarga Imran' },
  { nomor: 4, nama: 'An-Nisa', arti: 'Wanita' },
  { nomor: 5, nama: 'Al-Maidah', arti: 'Hidangan' },
  { nomor: 6, nama: 'Al-Anam', arti: 'Binatang Ternak' },
  { nomor: 7, nama: 'Al-Araf', arti: 'Tempat Tertinggi' },
  { nomor: 8, nama: 'Al-Anfal', arti: 'Rampasan Perang' },
  { nomor: 9, nama: 'At-Taubah', arti: 'Pengampunan' },
  { nomor: 10, nama: 'Yunus', arti: 'Nabi Yunus' },
  { nomor: 11, nama: 'Hud', arti: 'Nabi Hud' },
  { nomor: 12, nama: 'Yusuf', arti: 'Nabi Yusuf' },
  { nomor: 13, nama: 'Ar-Rad', arti: 'Guruh' },
  { nomor: 14, nama: 'Ibrahim', arti: 'Nabi Ibrahim' },
  { nomor: 15, nama: 'Al-Hijr', arti: 'Hijr' },
  { nomor: 16, nama: 'An-Nahl', arti: 'Lebah' },
  { nomor: 17, nama: 'Al-Isra', arti: 'Perjalanan Malam' },
  { nomor: 18, nama: 'Al-Kahf', arti: 'Gua' },
  { nomor: 19, nama: 'Maryam', arti: 'Maryam' },
  { nomor: 20, nama: 'Ta-Ha', arti: 'Ta Ha' },
  { nomor: 21, nama: 'Al-Anbiya', arti: 'Para Nabi' },
  { nomor: 22, nama: 'Al-Hajj', arti: 'Haji' },
  { nomor: 23, nama: 'Al-Muminun', arti: 'Orang-orang Mukmin' },
  { nomor: 24, nama: 'An-Nur', arti: 'Cahaya' },
  { nomor: 25, nama: 'Al-Furqan', arti: 'Pembeda' },
  { nomor: 26, nama: 'Asy-Syuara', arti: 'Para Penyair' },
  { nomor: 27, nama: 'An-Naml', arti: 'Semut' },
  { nomor: 28, nama: 'Al-Qasas', arti: 'Kisah-kisah' },
  { nomor: 29, nama: 'Al-Ankabut', arti: 'Laba-laba' },
  { nomor: 30, nama: 'Ar-Rum', arti: 'Romawi' },
  { nomor: 31, nama: 'Luqman', arti: 'Luqman' },
  { nomor: 32, nama: 'As-Sajdah', arti: 'Sujud' },
  { nomor: 33, nama: 'Al-Ahzab', arti: 'Golongan-golongan' },
  { nomor: 34, nama: 'Saba', arti: 'Saba' },
  { nomor: 35, nama: 'Fatir', arti: 'Pencipta' },
  { nomor: 36, nama: 'Yasin', arti: 'Yasin' },
  { nomor: 37, nama: 'As-Saffat', arti: 'Barisan-barisan' },
  { nomor: 38, nama: 'Sad', arti: 'Sad' },
  { nomor: 39, nama: 'Az-Zumar', arti: 'Rombongan-rombongan' },
  { nomor: 40, nama: 'Ghafir', arti: 'Yang Mengampuni' },
  { nomor: 41, nama: 'Fussilat', arti: 'Yang Dijelaskan' },
  { nomor: 42, nama: 'Asy-Syura', arti: 'Musyawarah' },
  { nomor: 43, nama: 'Az-Zukhruf', arti: 'Perhiasan' },
  { nomor: 44, nama: 'Ad-Dukhan', arti: 'Kabut' },
  { nomor: 45, nama: 'Al-Jasiyah', arti: 'Berlutut' },
  { nomor: 46, nama: 'Al-Ahqaf', arti: 'Bukit-bukit Pasir' },
  { nomor: 47, nama: 'Muhammad', arti: 'Nabi Muhammad' },
  { nomor: 48, nama: 'Al-Fath', arti: 'Kemenangan' },
  { nomor: 49, nama: 'Al-Hujurat', arti: 'Kamar-kamar' },
  { nomor: 50, nama: 'Qaf', arti: 'Qaf' },
  { nomor: 51, nama: 'Adz-Dzariyat', arti: 'Angin yang Menerbangkan' },
  { nomor: 52, nama: 'At-Tur', arti: 'Bukit' },
  { nomor: 53, nama: 'An-Najm', arti: 'Bintang' },
  { nomor: 54, nama: 'Al-Qamar', arti: 'Bulan' },
  { nomor: 55, nama: 'Ar-Rahman', arti: 'Yang Maha Pemurah' },
  { nomor: 56, nama: 'Al-Waqiah', arti: 'Hari Kiamat' },
  { nomor: 57, nama: 'Al-Hadid', arti: 'Besi' },
  { nomor: 58, nama: 'Al-Mujadilah', arti: 'Wanita yang Mengajukan Gugatan' },
  { nomor: 59, nama: 'Al-Hasyr', arti: 'Pengusiran' },
  { nomor: 60, nama: 'Al-Mumtahanah', arti: 'Wanita yang Diuji' },
  { nomor: 61, nama: 'As-Saff', arti: 'Barisan' },
  { nomor: 62, nama: 'Al-Jumuah', arti: 'Jumat' },
  { nomor: 63, nama: 'Al-Munafiqun', arti: 'Orang-orang Munafik' },
  { nomor: 64, nama: 'At-Taghabun', arti: 'Hari Dinampakkan Kesalahan' },
  { nomor: 65, nama: 'At-Talaq', arti: 'Cerai' },
  { nomor: 66, nama: 'At-Tahrim', arti: 'Mengharamkan' },
  { nomor: 67, nama: 'Al-Mulk', arti: 'Kerajaan' },
  { nomor: 68, nama: 'Al-Qalam', arti: 'Pena' },
  { nomor: 69, nama: 'Al-Haqqah', arti: 'Hari Kiamat' },
  { nomor: 70, nama: 'Al-Maarij', arti: 'Tempat-tempat Naik' },
  { nomor: 71, nama: 'Nuh', arti: 'Nabi Nuh' },
  { nomor: 72, nama: 'Al-Jinn', arti: 'Jin' },
  { nomor: 73, nama: 'Al-Muzzammil', arti: 'Orang yang Berselimut' },
  { nomor: 74, nama: 'Al-Muddaththir', arti: 'Orang yang Berkemul' },
  { nomor: 75, nama: 'Al-Qiyamah', arti: 'Hari Kebangkitan' },
  { nomor: 76, nama: 'Al-Insan', arti: 'Manusia' },
  { nomor: 77, nama: 'Al-Mursalat', arti: 'Malaikat yang Diutus' },
  { nomor: 78, nama: 'An-Naba', arti: 'Berita Besar' },
  { nomor: 79, nama: 'An-Naziat', arti: 'Malaikat yang Mencabut' },
  { nomor: 80, nama: 'Abasa', arti: 'Ia Bermuka Masam' },
  { nomor: 81, nama: 'At-Takwir', arti: 'Menggulung' },
  { nomor: 82, nama: 'Al-Infitar', arti: 'Terbelah' },
  { nomor: 83, nama: 'Al-Mutaffifin', arti: 'Orang-orang yang Curang' },
  { nomor: 84, nama: 'Al-Insyiqaq', arti: 'Terbelah' },
  { nomor: 85, nama: 'Al-Buruj', arti: 'Gugusan Bintang' },
  { nomor: 86, nama: 'At-Tariq', arti: 'Yang Datang di Malam Hari' },
  { nomor: 87, nama: 'Al-Ala', arti: 'Yang Paling Tinggi' },
  { nomor: 88, nama: 'Al-Ghasyiyah', arti: 'Hari Pembalasan' },
  { nomor: 89, nama: 'Al-Fajr', arti: 'Fajar' },
  { nomor: 90, nama: 'Al-Balad', arti: 'Negeri' },
  { nomor: 91, nama: 'Asy-Syams', arti: 'Matahari' },
  { nomor: 92, nama: 'Al-Lail', arti: 'Malam' },
  { nomor: 93, nama: 'Ad-Duha', arti: 'Waktu Dhuha' },
  { nomor: 94, nama: 'Al-Insyirah', arti: 'Melapangkan' },
  { nomor: 95, nama: 'At-Tin', arti: 'Buah Tin' },
  { nomor: 96, nama: 'Al-Alaq', arti: 'Segumpal Darah' },
  { nomor: 97, nama: 'Al-Qadr', arti: 'Kemuliaan' },
  { nomor: 98, nama: 'Al-Bayyinah', arti: 'Bukti yang Nyata' },
  { nomor: 99, nama: 'Az-Zalzalah', arti: 'Kegoncangan' },
  { nomor: 100, nama: 'Al-Adiyat', arti: 'Kuda yang Berlari Kencang' },
  { nomor: 101, nama: 'Al-Qariah', arti: 'Hari Kiamat' },
  { nomor: 102, nama: 'At-Takasur', arti: 'Bermegah-megahan' },
  { nomor: 103, nama: 'Al-Asr', arti: 'Waktu Asar' },
  { nomor: 104, nama: 'Al-Humazah', arti: 'Pengumpat' },
  { nomor: 105, nama: 'Al-Fil', arti: 'Gajah' },
  { nomor: 106, nama: 'Quraisy', arti: 'Suku Quraisy' },
  { nomor: 107, nama: 'Al-Maun', arti: 'Barang-barang yang Berguna' },
  { nomor: 108, nama: 'Al-Kausar', arti: 'Nikmat yang Banyak' },
  { nomor: 109, nama: 'Al-Kafirun', arti: 'Orang-orang Kafir' },
  { nomor: 110, nama: 'An-Nasr', arti: 'Pertolongan' },
  { nomor: 111, nama: 'Al-Lahab', arti: 'Api yang Bergejolak' },
  { nomor: 112, nama: 'Al-Ikhlas', arti: 'Ikhlas' },
  { nomor: 113, nama: 'Al-Falaq', arti: 'Waktu Subuh' },
  { nomor: 114, nama: 'An-Nas', arti: 'Manusia' },
] as const

export type Surah = typeof DAFTAR_SURAH[number]
